---
openapi: 3.0.0
info:
  title: Partner Callback API
  description: API callbacks that a merchant or ISV will implement as part of their integration with the Skipify platform. These are B2B integrations that Skipify's backend will make to the merchant's backend services. The Skipify team commonly refers to these as **Delegated Callbacks**
    <p/> 
    An example of a callback integration is the shipping and tax calculator. Skipify requests the merchant to provide shipping and tax details for an order based on the current shipping address selected by the customer. When a customer selects a shipping address in the Skipify UI, Skipify will orchestrate a B2B call to the merchant's implementation of the shipping-and-taxes service method. The results of this request are displayed in the Skipify UI - allowing the customer to be informed of their shipping options and the associate costs.
  contact:
    url: https://docs.skipify.com/docs
    email: support@skipify.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Skipify/partner-callback-api/1.0.1
tags:
- name: merchant-integrations
  description: Calls used by Skipify integration partners
paths:
  /shipping-and-taxes:
    post:
      tags:
      - merchant-integrations
      summary: Calculates shipping and tax for an order for the respective shipping options.
      description: Calculates the shipping and tax charges for an order for the respective shipping options.
      operationId: calculateShippingAndTax
      requestBody:
        description: Shipping and tax request payload.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShippingAndTaxRequest'
        required: true
      responses:
        '200':
          description: Shipping and tax calculated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShippingAndTaxResponse'
        '400':
          description: invalid input, object invalid
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Skipify/skipify-core-domain/1.0.1#/components/schemas/ExceptionResponse'
components:
  schemas:
    ShippingAndTaxRequest:
      required:
      - goCartOrderId
      - merchantOrderId
      - shippingAddress
      type: object
      properties:
        merchantOrderId:
          type: string
          example: someMerchantOrderId
        goCartOrderId:
          type: string
          format: uuid
          example: 77a051d8-be26-11eb-8529-0242ac130003
        shippingAddress:
          $ref: '#/components/schemas/ShippingAddress'
    ShippingAddress:
      required:
      - addressLocality
      - addressRegion
      - postalCode
      - shippingAddressId
      - streetAddress
      type: object
      properties:
        shippingAddressId:
          type: string
          format: uuid
          example: 53e2a852-be23-11eb-8529-0242ac130003
        streetAddress:
          type: string
          example: 123 Main Street
        addressLocality:
          type: string
          example: Denver
        addressRegion:
          type: string
          example: CO
        postalCode:
          type: string
          example: "80209"
    ShippingAndTaxResponse:
      required:
      - currencyCode
      - shippingAddressId
      type: object
      properties:
        shippingAddressId:
          type: string
          description: Send back the value provided in the request. This value is used for correlation and validation purposes.
          format: uuid
          example: 53e2a852-be23-11eb-8529-0242ac130003
        currencyCode:
          type: string
          description: The ISO 4217 three character currency code.
          format: iso4217
          example: USD
          default: USD
        shippingOptions:
          maxItems: 10
          minItems: 0
          uniqueItems: true
          type: array
          description: The collection of shipping options for the order can include zero to 10 shipping options.
          items:
            $ref: '#/components/schemas/Shipping'
        preferredShippingOptionId:
          maximum: 10
          minimum: 0
          type: integer
          description: The prefered pre-selected shipping option identifier ('id') from the shippingOptions array.
          example: 1
        tax:
          minimum: 0
          type: number
          description: The taxes for the order factoring in the shipping address.
          format: double
          example: 10.5
    Shipping:
      required:
      - name
      - price
      type: object
      properties:
        id:
          maximum: 10
          minimum: 0
          type: integer
          description: A numeric identifier for this option. This id is used to demaracate the default selected shipping option.
          example: 1
        name:
          type: string
          example: Ground Freight
        price:
          minimum: 0
          type: number
          format: double
          example: 25.98
      description: Details for a single shipping option. For instance, shipping for 2 day versus next day versus ground freight.